### Users create
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test Name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}


### Comics Index
GET http://localhost:3000/comics.json

### Comics Create
POST http://localhost:3000/comics.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODU4NDkxNjR9.EyBQJhYmF3C_T6CLKGsp4aW9tMc_9_UPTlHeVB0ORV8
Content-Type: application/json

{
  "title": "Test create action with authroication/logged in",
  "image": "test.png"
}


### Comics Show
GET http://localhost:3000/comics/1.json


### Comics Update
PATCH http://localhost:3000/comics/2.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODU4NDkxNjR9.EyBQJhYmF3C_T6CLKGsp4aW9tMc_9_UPTlHeVB0ORV8
Content-Type: application/json

{
  "title": "I love stars sooo much!!!!!",
  "image": "test.png"
}


### Comics Destroy
DELETE http://localhost:3000/comics/7.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODU4NDkxNjR9.EyBQJhYmF3C_T6CLKGsp4aW9tMc_9_UPTlHeVB0ORV8