### Comics Index
GET http://localhost:3000/comics.json

### Comics Create
POST http://localhost:3000/comics.json
Content-Type: application/json

{
  "title": "Test create action",
  "image": "test.png"
}


### Comics Show
GET http://localhost:3000/comics/1.json


### Comics Update
PATCH http://localhost:3000/comics/4.json
Content-Type: application/json

{
  "title": "updated updated",
  "image": "update.png"
}


### Comics Destroy
DELETE http://localhost:3000/comics/5.json